name: Daily App-Price JSON Tracker (Dynamic Inputs)

/*------------- 触发器 -------------*/
on:
  # 每天 02:02 UTC 自动跑
  schedule:
    - cron: '2 2 * * *'

  # 手动触发时可传入参数
  workflow_dispatch:
    inputs:
      app_ids:
        description: 'Space-separated App Store numeric IDs'
        required: false
        default: '414478124 544007664 1315744137'
      countries:
        description: 'Space-separated ISO country codes'
        required: false
        default: 'us cn jp'

/*------------- 作业 -------------*/
jobs:
  fetch:
    runs-on: ubuntu-latest

    # 避免同一分支跑多次
    concurrency:
      group: price-json-${{ github.ref }}
      cancel-in-progress: true

    # 把 inputs—or-default 写进环境变量
    env:
      APP_IDS: ${{ inputs.app_ids   || '414478124 544007664 1315744137' }}
      COUNTRY_LIST: ${{ inputs.countries || 'us cn jp' }}

    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Fetch & append prices (多 ID × 多区)
        run: |
          set -e
          TODAY=$(date -u '+%F')

          for APP_ID in ${APP_IDS}; do
            echo "==== ${APP_ID} ===="
            for CC in ${COUNTRY_LIST}; do
              echo "► ${CC}"
              curl -sS "https://itunes.apple.com/lookup?id=${APP_ID}&country=${CC}" -o resp.json

              PRICE=$(jq -r '.results[0].price // .results[0].trackPrice // 0' resp.json)
              CUR=$(jq -r '.results[0].currency // .results[0].currencyCode // "USD"' resp.json)
              FILE="price_${APP_ID}_${CC}.json"

              if [ -f "$FILE" ]; then
                jq --arg d "$TODAY" --argjson p "$PRICE" --arg c "$CUR" \
                   '. += [{"date":$d,"price":$p,"currency":$c}]' "$FILE" > tmp && mv tmp "$FILE"
              else
                echo "[{\"date\":\"$TODAY\",\"price\":$PRICE,\"currency\":\"$CUR\"}]" > "$FILE"
              fi
            done
          done

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'price_*.json'
          message: "chore: update prices on $(date -u '+%F')"
